version: '3.5'

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web
    ports:
      - '3000:3000'
    depends_on:
      - app
    volumes:
      # Required to sync file changes.
      - ./client:/usr/src/web
      # Required to not break node modules.
      - /usr/src/web/node_modules
      # Required for next to do it's thing.
      - /usr/src/web/.next
              
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env # Specify the path to your .env file
    volumes:
      - ./server:/app/server
      

