version: '3.5'

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web
    ports:
      - '3000:3000'
    depends_on:
      - app
    volumes:
      # Required to sync file changes.
      - ./client:/usr/src/web
      # Required to not break node modules.
      - /usr/src/web/node_modules
      # Required for next to do it's thing.
      - /usr/src/web/.next
    # deploy:
    #     resources:
    #         limits:
    #           cpus: 0.50
    #           memory: 512M
    #         reservations:
    #           cpus: 0.25
    #           memory: 128M
              
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env # Specify the path to your .env file
    # depends_on:
    #   -  mongodb
    volumes:
      - ./server:/app/server
    # deploy:
    #     resources:
    #         limits:
    #           cpus: 0.50
    #           memory: 512M
    #         reservations:
    #           cpus: 0.25
    #           memory: 128M
      

#   mongodb: 
#     container_name: mongo
#     image: mongo:latest
#     ports: 
#     - '27017:27017'
#     volumes:
#       - data:/data/db
# volumes:
#   data:
