import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers";
import Navbar from '@/components/navbar';
import Footer from '@/components/Footer';
import React from 'react'; // Import React for StrictMode

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  excludeNavbarFooter = false, // Add a prop to conditionally exclude Navbar and Footer
}: {
  children: React.ReactNode,
  excludeNavbarFooter?: boolean,
}) {
  return (
    <React.StrictMode>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <Navbar />
            <div className="content">
              {children}
            </div>
            {!excludeNavbarFooter && <Footer />}
          </Providers>
        </body>
      </html>
    </React.StrictMode>
  )
}
