import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";
import React from "react"; // Import React for StrictMode
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";


const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "th" }];
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: any;
}) {
  let messages;
  try {
    messages = (await import(`@/messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <React.StrictMode>
      <html lang={locale}>
        <body className={inter.className}>
          <Providers>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <Navbar />
              <div className="content">{children}</div>
              <Footer />
            </NextIntlClientProvider>
          </Providers>
        </body>
      </html>
    </React.StrictMode>
  );
}
